#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_LapTop")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchitiethoadon(chitiethoadon instance);
    partial void Updatechitiethoadon(chitiethoadon instance);
    partial void Deletechitiethoadon(chitiethoadon instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void Insertdanhmuc(danhmuc instance);
    partial void Updatedanhmuc(danhmuc instance);
    partial void Deletedanhmuc(danhmuc instance);
    partial void Insertgia(gia instance);
    partial void Updategia(gia instance);
    partial void Deletegia(gia instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertkhach(khach instance);
    partial void Updatekhach(khach instance);
    partial void Deletekhach(khach instance);
    partial void Insertnhacungcap(nhacungcap instance);
    partial void Updatenhacungcap(nhacungcap instance);
    partial void Deletenhacungcap(nhacungcap instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_LapTopConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chitiethoadon> chitiethoadons
		{
			get
			{
				return this.GetTable<chitiethoadon>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<danhmuc> danhmucs
		{
			get
			{
				return this.GetTable<danhmuc>();
			}
		}
		
		public System.Data.Linq.Table<gia> gias
		{
			get
			{
				return this.GetTable<gia>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<khach> khaches
		{
			get
			{
				return this.GetTable<khach>();
			}
		}
		
		public System.Data.Linq.Table<nhacungcap> nhacungcaps
		{
			get
			{
				return this.GetTable<nhacungcap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitiethoadons")]
	public partial class chitiethoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_hd_chi_tiet;
		
		private int _ma_hd;
		
		private int _ma_san_pham;
		
		private int _so_luong;
		
		private int _gia_goc;
		
		private int _gia_khuyen_mai;
		
		private EntityRef<sanpham> _sanpham;
		
		private EntityRef<hoadon> _hoadon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_hd_chi_tietChanging(int value);
    partial void Onma_hd_chi_tietChanged();
    partial void Onma_hdChanging(int value);
    partial void Onma_hdChanged();
    partial void Onma_san_phamChanging(int value);
    partial void Onma_san_phamChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void Ongia_gocChanging(int value);
    partial void Ongia_gocChanged();
    partial void Ongia_khuyen_maiChanging(int value);
    partial void Ongia_khuyen_maiChanged();
    #endregion
		
		public chitiethoadon()
		{
			this._sanpham = default(EntityRef<sanpham>);
			this._hoadon = default(EntityRef<hoadon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_hd_chi_tiet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_hd_chi_tiet
		{
			get
			{
				return this._ma_hd_chi_tiet;
			}
			set
			{
				if ((this._ma_hd_chi_tiet != value))
				{
					this.Onma_hd_chi_tietChanging(value);
					this.SendPropertyChanging();
					this._ma_hd_chi_tiet = value;
					this.SendPropertyChanged("ma_hd_chi_tiet");
					this.Onma_hd_chi_tietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_hd", DbType="Int NOT NULL")]
		public int ma_hd
		{
			get
			{
				return this._ma_hd;
			}
			set
			{
				if ((this._ma_hd != value))
				{
					if (this._hoadon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_hdChanging(value);
					this.SendPropertyChanging();
					this._ma_hd = value;
					this.SendPropertyChanged("ma_hd");
					this.Onma_hdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_san_pham", DbType="Int NOT NULL")]
		public int ma_san_pham
		{
			get
			{
				return this._ma_san_pham;
			}
			set
			{
				if ((this._ma_san_pham != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ma_san_pham = value;
					this.SendPropertyChanged("ma_san_pham");
					this.Onma_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_goc", DbType="Int NOT NULL")]
		public int gia_goc
		{
			get
			{
				return this._gia_goc;
			}
			set
			{
				if ((this._gia_goc != value))
				{
					this.Ongia_gocChanging(value);
					this.SendPropertyChanging();
					this._gia_goc = value;
					this.SendPropertyChanged("gia_goc");
					this.Ongia_gocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_khuyen_mai", DbType="Int NOT NULL")]
		public int gia_khuyen_mai
		{
			get
			{
				return this._gia_khuyen_mai;
			}
			set
			{
				if ((this._gia_khuyen_mai != value))
				{
					this.Ongia_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._gia_khuyen_mai = value;
					this.SendPropertyChanged("gia_khuyen_mai");
					this.Ongia_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitiethoadon", Storage="_sanpham", ThisKey="ma_san_pham", OtherKey="ma_sp", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.chitiethoadons.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.chitiethoadons.Add(this);
						this._ma_san_pham = value.ma_sp;
					}
					else
					{
						this._ma_san_pham = default(int);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_chitiethoadon", Storage="_hoadon", ThisKey="ma_hd", OtherKey="ma_hd", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public hoadon hoadon
		{
			get
			{
				return this._hoadon.Entity;
			}
			set
			{
				hoadon previousValue = this._hoadon.Entity;
				if (((previousValue != value) 
							|| (this._hoadon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoadon.Entity = null;
						previousValue.chitiethoadons.Remove(this);
					}
					this._hoadon.Entity = value;
					if ((value != null))
					{
						value.chitiethoadons.Add(this);
						this._ma_hd = value.ma_hd;
					}
					else
					{
						this._ma_hd = default(int);
					}
					this.SendPropertyChanged("hoadon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanphams")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_sp;
		
		private string _ten_sp;
		
		private int _ma_gia;
		
		private int _ma_ncc;
		
		private int _ma_danh_muc;
		
		private bool _trang_thai;
		
		private string _ghi_chu;
		
		private string _xuat_xu;
		
		private string _mo_ta;
		
		private string _hinh_anh;
		
		private EntitySet<chitiethoadon> _chitiethoadons;
		
		private EntityRef<danhmuc> _danhmuc;
		
		private EntityRef<gia> _gia;
		
		private EntityRef<nhacungcap> _nhacungcap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_spChanging(int value);
    partial void Onma_spChanged();
    partial void Onten_spChanging(string value);
    partial void Onten_spChanged();
    partial void Onma_giaChanging(int value);
    partial void Onma_giaChanged();
    partial void Onma_nccChanging(int value);
    partial void Onma_nccChanged();
    partial void Onma_danh_mucChanging(int value);
    partial void Onma_danh_mucChanged();
    partial void Ontrang_thaiChanging(bool value);
    partial void Ontrang_thaiChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onxuat_xuChanging(string value);
    partial void Onxuat_xuChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    #endregion
		
		public sanpham()
		{
			this._chitiethoadons = new EntitySet<chitiethoadon>(new Action<chitiethoadon>(this.attach_chitiethoadons), new Action<chitiethoadon>(this.detach_chitiethoadons));
			this._danhmuc = default(EntityRef<danhmuc>);
			this._gia = default(EntityRef<gia>);
			this._nhacungcap = default(EntityRef<nhacungcap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_sp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_sp
		{
			get
			{
				return this._ma_sp;
			}
			set
			{
				if ((this._ma_sp != value))
				{
					this.Onma_spChanging(value);
					this.SendPropertyChanging();
					this._ma_sp = value;
					this.SendPropertyChanged("ma_sp");
					this.Onma_spChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_sp", DbType="NVarChar(MAX)")]
		public string ten_sp
		{
			get
			{
				return this._ten_sp;
			}
			set
			{
				if ((this._ten_sp != value))
				{
					this.Onten_spChanging(value);
					this.SendPropertyChanging();
					this._ten_sp = value;
					this.SendPropertyChanged("ten_sp");
					this.Onten_spChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_gia", DbType="Int NOT NULL")]
		public int ma_gia
		{
			get
			{
				return this._ma_gia;
			}
			set
			{
				if ((this._ma_gia != value))
				{
					if (this._gia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_giaChanging(value);
					this.SendPropertyChanging();
					this._ma_gia = value;
					this.SendPropertyChanged("ma_gia");
					this.Onma_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_ncc", DbType="Int NOT NULL")]
		public int ma_ncc
		{
			get
			{
				return this._ma_ncc;
			}
			set
			{
				if ((this._ma_ncc != value))
				{
					if (this._nhacungcap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_nccChanging(value);
					this.SendPropertyChanging();
					this._ma_ncc = value;
					this.SendPropertyChanged("ma_ncc");
					this.Onma_nccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_danh_muc", DbType="Int NOT NULL")]
		public int ma_danh_muc
		{
			get
			{
				return this._ma_danh_muc;
			}
			set
			{
				if ((this._ma_danh_muc != value))
				{
					if (this._danhmuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_danh_mucChanging(value);
					this.SendPropertyChanging();
					this._ma_danh_muc = value;
					this.SendPropertyChanged("ma_danh_muc");
					this.Onma_danh_mucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="Bit NOT NULL")]
		public bool trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(MAX)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuat_xu", DbType="NVarChar(MAX)")]
		public string xuat_xu
		{
			get
			{
				return this._xuat_xu;
			}
			set
			{
				if ((this._xuat_xu != value))
				{
					this.Onxuat_xuChanging(value);
					this.SendPropertyChanging();
					this._xuat_xu = value;
					this.SendPropertyChanged("xuat_xu");
					this.Onxuat_xuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(MAX)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="NVarChar(MAX)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitiethoadon", Storage="_chitiethoadons", ThisKey="ma_sp", OtherKey="ma_san_pham")]
		public EntitySet<chitiethoadon> chitiethoadons
		{
			get
			{
				return this._chitiethoadons;
			}
			set
			{
				this._chitiethoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_danhmuc", ThisKey="ma_danh_muc", OtherKey="ma_danh_muc", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public danhmuc danhmuc
		{
			get
			{
				return this._danhmuc.Entity;
			}
			set
			{
				danhmuc previousValue = this._danhmuc.Entity;
				if (((previousValue != value) 
							|| (this._danhmuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._danhmuc.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._danhmuc.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._ma_danh_muc = value.ma_danh_muc;
					}
					else
					{
						this._ma_danh_muc = default(int);
					}
					this.SendPropertyChanged("danhmuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gia_sanpham", Storage="_gia", ThisKey="ma_gia", OtherKey="ma_gia", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public gia gia
		{
			get
			{
				return this._gia.Entity;
			}
			set
			{
				gia previousValue = this._gia.Entity;
				if (((previousValue != value) 
							|| (this._gia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gia.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._gia.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._ma_gia = value.ma_gia;
					}
					else
					{
						this._ma_gia = default(int);
					}
					this.SendPropertyChanged("gia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_sanpham", Storage="_nhacungcap", ThisKey="ma_ncc", OtherKey="ma_nha_cung_cap", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public nhacungcap nhacungcap
		{
			get
			{
				return this._nhacungcap.Entity;
			}
			set
			{
				nhacungcap previousValue = this._nhacungcap.Entity;
				if (((previousValue != value) 
							|| (this._nhacungcap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhacungcap.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._nhacungcap.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._ma_ncc = value.ma_nha_cung_cap;
					}
					else
					{
						this._ma_ncc = default(int);
					}
					this.SendPropertyChanged("nhacungcap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhmucs")]
	public partial class danhmuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_danh_muc;
		
		private string _ten_danh_muc;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_danh_mucChanging(int value);
    partial void Onma_danh_mucChanged();
    partial void Onten_danh_mucChanging(string value);
    partial void Onten_danh_mucChanged();
    #endregion
		
		public danhmuc()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_danh_muc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_danh_muc
		{
			get
			{
				return this._ma_danh_muc;
			}
			set
			{
				if ((this._ma_danh_muc != value))
				{
					this.Onma_danh_mucChanging(value);
					this.SendPropertyChanging();
					this._ma_danh_muc = value;
					this.SendPropertyChanged("ma_danh_muc");
					this.Onma_danh_mucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_danh_muc", DbType="NVarChar(MAX)")]
		public string ten_danh_muc
		{
			get
			{
				return this._ten_danh_muc;
			}
			set
			{
				if ((this._ten_danh_muc != value))
				{
					this.Onten_danh_mucChanging(value);
					this.SendPropertyChanging();
					this._ten_danh_muc = value;
					this.SendPropertyChanged("ten_danh_muc");
					this.Onten_danh_mucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_sanphams", ThisKey="ma_danh_muc", OtherKey="ma_danh_muc")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gias")]
	public partial class gia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_gia;
		
		private int _gia_goc;
		
		private int _gia_khuyen_mai;
		
		private System.DateTime _ngay_ap_dung;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_giaChanging(int value);
    partial void Onma_giaChanged();
    partial void Ongia_gocChanging(int value);
    partial void Ongia_gocChanged();
    partial void Ongia_khuyen_maiChanging(int value);
    partial void Ongia_khuyen_maiChanged();
    partial void Onngay_ap_dungChanging(System.DateTime value);
    partial void Onngay_ap_dungChanged();
    #endregion
		
		public gia()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_gia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_gia
		{
			get
			{
				return this._ma_gia;
			}
			set
			{
				if ((this._ma_gia != value))
				{
					this.Onma_giaChanging(value);
					this.SendPropertyChanging();
					this._ma_gia = value;
					this.SendPropertyChanged("ma_gia");
					this.Onma_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_goc", DbType="Int NOT NULL")]
		public int gia_goc
		{
			get
			{
				return this._gia_goc;
			}
			set
			{
				if ((this._gia_goc != value))
				{
					this.Ongia_gocChanging(value);
					this.SendPropertyChanging();
					this._gia_goc = value;
					this.SendPropertyChanged("gia_goc");
					this.Ongia_gocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_khuyen_mai", DbType="Int NOT NULL")]
		public int gia_khuyen_mai
		{
			get
			{
				return this._gia_khuyen_mai;
			}
			set
			{
				if ((this._gia_khuyen_mai != value))
				{
					this.Ongia_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._gia_khuyen_mai = value;
					this.SendPropertyChanged("gia_khuyen_mai");
					this.Ongia_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_ap_dung", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_ap_dung
		{
			get
			{
				return this._ngay_ap_dung;
			}
			set
			{
				if ((this._ngay_ap_dung != value))
				{
					this.Onngay_ap_dungChanging(value);
					this.SendPropertyChanging();
					this._ngay_ap_dung = value;
					this.SendPropertyChanged("ngay_ap_dung");
					this.Onngay_ap_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gia_sanpham", Storage="_sanphams", ThisKey="ma_gia", OtherKey="ma_gia")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.gia = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.gia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadons")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_hd;
		
		private int _ma_kh;
		
		private int _tong_tien;
		
		private int _trang_thai;
		
		private string _ghi_chu;
		
		private System.DateTime _ngay_tao;
		
		private EntitySet<chitiethoadon> _chitiethoadons;
		
		private EntityRef<khach> _khach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_hdChanging(int value);
    partial void Onma_hdChanged();
    partial void Onma_khChanging(int value);
    partial void Onma_khChanged();
    partial void Ontong_tienChanging(int value);
    partial void Ontong_tienChanged();
    partial void Ontrang_thaiChanging(int value);
    partial void Ontrang_thaiChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    #endregion
		
		public hoadon()
		{
			this._chitiethoadons = new EntitySet<chitiethoadon>(new Action<chitiethoadon>(this.attach_chitiethoadons), new Action<chitiethoadon>(this.detach_chitiethoadons));
			this._khach = default(EntityRef<khach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_hd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_hd
		{
			get
			{
				return this._ma_hd;
			}
			set
			{
				if ((this._ma_hd != value))
				{
					this.Onma_hdChanging(value);
					this.SendPropertyChanging();
					this._ma_hd = value;
					this.SendPropertyChanged("ma_hd");
					this.Onma_hdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_kh", DbType="Int NOT NULL")]
		public int ma_kh
		{
			get
			{
				return this._ma_kh;
			}
			set
			{
				if ((this._ma_kh != value))
				{
					if (this._khach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_khChanging(value);
					this.SendPropertyChanging();
					this._ma_kh = value;
					this.SendPropertyChanged("ma_kh");
					this.Onma_khChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Int NOT NULL")]
		public int tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="Int NOT NULL")]
		public int trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(MAX)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_chitiethoadon", Storage="_chitiethoadons", ThisKey="ma_hd", OtherKey="ma_hd")]
		public EntitySet<chitiethoadon> chitiethoadons
		{
			get
			{
				return this._chitiethoadons;
			}
			set
			{
				this._chitiethoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hoadon", Storage="_khach", ThisKey="ma_kh", OtherKey="id_Khach", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public khach khach
		{
			get
			{
				return this._khach.Entity;
			}
			set
			{
				khach previousValue = this._khach.Entity;
				if (((previousValue != value) 
							|| (this._khach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khach.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._khach.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._ma_kh = value.id_Khach;
					}
					else
					{
						this._ma_kh = default(int);
					}
					this.SendPropertyChanged("khach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon = this;
		}
		
		private void detach_chitiethoadons(chitiethoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhangs")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_khach_hang;
		
		private string _email;
		
		private string _password;
		
		private string _UserName;
		
		private string _ComfirmPassWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_khach_hangChanging(int value);
    partial void Onma_khach_hangChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnComfirmPassWordChanging(string value);
    partial void OnComfirmPassWordChanged();
    #endregion
		
		public khachhang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_khach_hang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_khach_hang
		{
			get
			{
				return this._ma_khach_hang;
			}
			set
			{
				if ((this._ma_khach_hang != value))
				{
					this.Onma_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._ma_khach_hang = value;
					this.SendPropertyChanged("ma_khach_hang");
					this.Onma_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComfirmPassWord", DbType="NVarChar(MAX)")]
		public string ComfirmPassWord
		{
			get
			{
				return this._ComfirmPassWord;
			}
			set
			{
				if ((this._ComfirmPassWord != value))
				{
					this.OnComfirmPassWordChanging(value);
					this.SendPropertyChanging();
					this._ComfirmPassWord = value;
					this.SendPropertyChanged("ComfirmPassWord");
					this.OnComfirmPassWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachs")]
	public partial class khach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Khach;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _ComfirmPassWord;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_KhachChanging(int value);
    partial void Onid_KhachChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnComfirmPassWordChanging(string value);
    partial void OnComfirmPassWordChanged();
    #endregion
		
		public khach()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Khach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Khach
		{
			get
			{
				return this._id_Khach;
			}
			set
			{
				if ((this._id_Khach != value))
				{
					this.Onid_KhachChanging(value);
					this.SendPropertyChanging();
					this._id_Khach = value;
					this.SendPropertyChanged("id_Khach");
					this.Onid_KhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComfirmPassWord", DbType="NVarChar(MAX)")]
		public string ComfirmPassWord
		{
			get
			{
				return this._ComfirmPassWord;
			}
			set
			{
				if ((this._ComfirmPassWord != value))
				{
					this.OnComfirmPassWordChanging(value);
					this.SendPropertyChanging();
					this._ComfirmPassWord = value;
					this.SendPropertyChanged("ComfirmPassWord");
					this.OnComfirmPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hoadon", Storage="_hoadons", ThisKey="id_Khach", OtherKey="ma_kh")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khach = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhacungcaps")]
	public partial class nhacungcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_nha_cung_cap;
		
		private string _ten_nha_cung_cap;
		
		private string _dia_chi;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_nha_cung_capChanging(int value);
    partial void Onma_nha_cung_capChanged();
    partial void Onten_nha_cung_capChanging(string value);
    partial void Onten_nha_cung_capChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    #endregion
		
		public nhacungcap()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nha_cung_cap", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_nha_cung_cap
		{
			get
			{
				return this._ma_nha_cung_cap;
			}
			set
			{
				if ((this._ma_nha_cung_cap != value))
				{
					this.Onma_nha_cung_capChanging(value);
					this.SendPropertyChanging();
					this._ma_nha_cung_cap = value;
					this.SendPropertyChanged("ma_nha_cung_cap");
					this.Onma_nha_cung_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nha_cung_cap", DbType="NVarChar(MAX)")]
		public string ten_nha_cung_cap
		{
			get
			{
				return this._ten_nha_cung_cap;
			}
			set
			{
				if ((this._ten_nha_cung_cap != value))
				{
					this.Onten_nha_cung_capChanging(value);
					this.SendPropertyChanging();
					this._ten_nha_cung_cap = value;
					this.SendPropertyChanged("ten_nha_cung_cap");
					this.Onten_nha_cung_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(MAX)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_sanpham", Storage="_sanphams", ThisKey="ma_nha_cung_cap", OtherKey="ma_ncc")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = null;
		}
	}
}
#pragma warning restore 1591
